# fly.toml app configuration file generated for cat-topia on 2023-08-08T18:37:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cat-topia"
primary_region = "ams"

[build]
  dockerfile = "./docker/apps/cat-topia/production/Dockerfile"

[env]
  PORT = "8080"
  PRETTY_PRINT = "YES"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
